name: Coins
main: zFastSlaying\Coins
version: 1.0.0
api: 3.0.0-ALPHA12
author: zFastSlaying
commands:
  Coins:
    description: Coins Command
    aliases: [coins]
  AddCoins:
    description: AddCoins Command
    aliases: [addcoins]